from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

LOGIN_ERROR = "需要登录"

# Any-of groups are inner tuples joined by AND across names; outer list is OR.
PLATFORM_SENTINELS: dict[str, tuple[tuple[str, ...], ...]] = {
    "xhs": (("web_session",), ("a1",)),
    "bili": (("DedeUserID", "SESSDATA"),),
    "zhihu": (("z_c0",),),
    "dy": (("sessionid",), ("sid_guard",)),
    "wb": (("SUB",), ("WBPSESS",)),
}

_LOGIN_PATH = re.compile(r"/(login|passport|signin|account/login)(/|\?|$)", re.I)
_LOGIN_TITLE = re.compile(r"(请登录|掃碼登錄|扫码登录|验证码)")
_LOGIN_PHRASES = (
    "请先登录后查看完整内容",
    "登录解锁全文",
    "登录后即可查看",
    "登录后查看完整内容",
    "請先登入後查看完整內容",
)


def cookies_dir(root: Path | None = None) -> Path:
    if root is not None:
        return Path(root)
    env = (os.environ.get("COOKIES_DIR") or os.environ.get("SOCIAL_COOKIES_DIR") or "").strip()
    if env:
        return Path(env)
    from backend.settings import ROOT

    return ROOT / "data" / "cookies"


def infer_platform(url: str, explicit: str | None = None) -> str | None:
    if explicit:
        key = explicit.strip().lower()
        return key if key in PLATFORM_SENTINELS else None
    host = (urlparse(url).hostname or "").lower()
    if "xiaohongshu" in host or host.endswith("xhs.com"):
        return "xhs"
    if "bilibili" in host:
        return "bili"
    if "zhihu.com" in host:
        return "zhihu"
    if "douyin.com" in host:
        return "dy"
    if "weibo.com" in host or host.endswith("weibo.cn"):
        return "wb"
    return None


def _cookie_names(cookies: list[dict[str, Any]]) -> set[str]:
    return {str(item.get("name")) for item in cookies if item.get("name")}


def has_login_sentinels(platform: str, cookies: list[dict[str, Any]]) -> bool:
    groups = PLATFORM_SENTINELS.get(platform)
    if not groups:
        return False
    names = _cookie_names(cookies)
    return any(all(key in names for key in group) for group in groups)


def cookies_json_to_netscape(cookies: list[dict[str, Any]]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# This file was generated by Crawler Agent. Do not share.", ""]
    for item in cookies:
        name = str(item.get("name") or "")
        value = str(item.get("value") or "")
        if not name:
            continue
        domain = str(item.get("domain") or "")
        path = str(item.get("path") or "/")
        secure = "TRUE" if item.get("secure") else "FALSE"
        raw_exp = item.get("expires")
        if raw_exp in (None, "", -1):
            expires = "0"
        else:
            expires = str(int(float(raw_exp)))
        host_only = domain.startswith(".")
        include_sub = "TRUE" if host_only else "FALSE"
        if item.get("httpOnly"):
            domain_col = f"#HttpOnly_{domain}"
        else:
            domain_col = domain
        lines.append("\t".join([domain_col, include_sub, path, secure, expires, name, value]))
    return "\n".join(lines) + "\n"


def detect_login_wall(*, url: str, title: str, html: str) -> bool:
    path_and_query = urlparse(url).path + ("?" + urlparse(url).query if urlparse(url).query else "")
    if _LOGIN_PATH.search(path_and_query) or _LOGIN_PATH.search(url):
        return True
    if _LOGIN_TITLE.search(title or ""):
        return True
    snippet = re.sub(r"\s+", "", (html or "")[:4000])
    return any(phrase.replace(" ", "") in snippet for phrase in _LOGIN_PHRASES)


def _host_matches(cookie_domain: str, host: str) -> bool:
    domain = (cookie_domain or "").lstrip(".").lower()
    host = host.lower()
    if not domain:
        return False
    return host == domain or host.endswith("." + domain)


class CookieJar:
    def __init__(self, root: Path | None = None) -> None:
        self.root = cookies_dir(root)

    def storage_path(self, platform: str) -> Path:
        return self.root / f"{platform}.json"

    def netscape_path(self, platform: str) -> Path:
        return self.root / f"{platform}.netscape.txt"

    def load_storage_state(self, platform: str) -> dict[str, Any] | None:
        path = self.storage_path(platform)
        if not path.is_file():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        if not isinstance(data, dict):
            return None
        return data

    def save_storage_state(self, platform: str, state: dict[str, Any]) -> Path:
        cookies = list(state.get("cookies") or [])
        if not has_login_sentinels(platform, cookies):
            raise ValueError("未检测到有效登录特征，拒绝写出游客 Cookie")
        self.root.mkdir(parents=True, exist_ok=True)
        payload = {"cookies": cookies, "origins": list(state.get("origins") or [])}
        path = self.storage_path(platform)
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        self.netscape_path(platform).write_text(cookies_json_to_netscape(cookies), encoding="utf-8")
        return path

    def netscape_for_url(self, url: str) -> Path | None:
        platform = infer_platform(url)
        if not platform:
            return None
        return self.ensure_netscape(platform)

    def storage_state_for_url(self, url: str) -> dict[str, Any] | None:
        platform = infer_platform(url)
        if not platform:
            return None
        state = self.load_storage_state(platform)
        cookies = list((state or {}).get("cookies") or [])
        if not has_login_sentinels(platform, cookies):
            return None
        return state

    def ensure_netscape(self, platform: str) -> Path | None:
        state = self.load_storage_state(platform)
        cookies = list((state or {}).get("cookies") or [])
        if not has_login_sentinels(platform, cookies):
            return None
        path = self.netscape_path(platform)
        if not path.is_file():
            self.root.mkdir(parents=True, exist_ok=True)
            path.write_text(cookies_json_to_netscape(cookies), encoding="utf-8")
        return path

    def cookies_for_url(self, url: str) -> list[dict[str, Any]]:
        host = (urlparse(url).hostname or "").lower()
        platform = infer_platform(url)
        collected: list[dict[str, Any]] = []
        seen: set[str] = set()
        if platform:
            state = self.load_storage_state(platform)
            for item in (state or {}).get("cookies") or []:
                name = str(item.get("name") or "")
                if name and name not in seen and _host_matches(str(item.get("domain") or ""), host):
                    collected.append(item)
                    seen.add(name)
        for path in sorted(self.root.glob("*.json")) if self.root.is_dir() else []:
            if platform and path.name == f"{platform}.json":
                continue
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            for item in data.get("cookies") or []:
                name = str(item.get("name") or "")
                if name and name not in seen and _host_matches(str(item.get("domain") or ""), host):
                    collected.append(item)
                    seen.add(name)
        return collected

    def cookie_header(self, url: str) -> str:
        return "; ".join(
            f"{item['name']}={item.get('value') or ''}" for item in self.cookies_for_url(url) if item.get("name")
        )

    def configured_platforms(self) -> list[dict[str, Any]]:
        rows = []
        for platform in PLATFORM_SENTINELS:
            state = self.load_storage_state(platform)
            cookies = list((state or {}).get("cookies") or [])
            rows.append({"platform": platform, "configured": has_login_sentinels(platform, cookies)})
        return rows


def session_status_line(jar: CookieJar | None = None) -> str:
    rows = (jar or CookieJar()).configured_platforms()
    parts = [f"{item['platform']}={'是' if item['configured'] else '否'}" for item in rows]
    return "本机登录态（仅布尔，不含 Cookie 值）：" + "，".join(parts) + "。"
